// Tests for bump-version.mjs. Run: node --test scripts/
import { test, beforeEach, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  readVersions,
  assertConsistent,
  compareVersions,
  bumpVersion,
  assertTagMatches,
} from './bump-version.mjs';

const FILES = [
  'package.json',
  'package-lock.json',
  'src-tauri/tauri.conf.json',
  'src-tauri/Cargo.toml',
  'src-tauri/Cargo.lock',
];

// Minimal fixtures. Dependencies deliberately share the app's version to prove they are not touched.
function fixtures(v, overrides = {}) {
  const x = { packageJson: v, lockRoot: v, lockPackage: v, tauri: v, cargoToml: v, cargoLock: v, ...overrides };
  return {
    'package.json': `{\n  "name": "demo",\n  "private": true,\n  "version": "${x.packageJson}",\n  "scripts": {\n    "test": "jest"\n  }\n}\n`,
    'package-lock.json': `{\n  "name": "demo",\n  "version": "${x.lockRoot}",\n  "lockfileVersion": 3,\n  "requires": true,\n  "packages": {\n    "": {\n      "name": "demo",\n      "version": "${x.lockPackage}",\n      "dependencies": {\n        "left-pad": "^${v}"\n      }\n    },\n    "node_modules/left-pad": {\n      "version": "${v}",\n      "license": "MIT"\n    }\n  }\n}\n`,
    'src-tauri/tauri.conf.json': `{\n  "$schema": "../node_modules/@tauri-apps/cli/config.schema.json",\n  "productName": "Demo",\n  "version": "${x.tauri}",\n  "identifier": "com.example.demo"\n}\n`,
    'src-tauri/Cargo.toml': `[package]\nname = "app"\nversion = "${x.cargoToml}"\ndescription = "Demo"\n\n[dependencies]\nlog = "0.4"\n`,
    'src-tauri/Cargo.lock': `# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "app"\nversion = "${x.cargoLock}"\ndependencies = [\n "log",\n]\n\n[[package]]\nname = "log"\nversion = "${v}"\n`,
  };
}

let dir;

function setup(v = '1.0.0', overrides = {}) {
  const files = fixtures(v, overrides);
  for (const [rel, content] of Object.entries(files)) {
    const full = path.join(dir, rel);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, content);
  }
  return files;
}

const read = (rel) => fs.readFileSync(path.join(dir, rel), 'utf8');

beforeEach(() => {
  dir = fs.mkdtempSync(path.join(os.tmpdir(), 'bump-version-'));
});
afterEach(() => {
  fs.rmSync(dir, { recursive: true, force: true });
});

test('bumps all six version locations and leaves dependency versions untouched', () => {
  setup('1.0.0');
  const result = bumpVersion(dir, '1.2.3');
  assert.deepEqual(result, { from: '1.0.0', to: '1.2.3' });
  assert.deepEqual(readVersions(dir), {
    packageJson: '1.2.3',
    packageLockRoot: '1.2.3',
    packageLockPackage: '1.2.3',
    tauriConf: '1.2.3',
    cargoToml: '1.2.3',
    cargoLock: '1.2.3',
  });
  assert.match(read('package-lock.json'), /"node_modules\/left-pad": \{\n {6}"version": "1\.0\.0"/);
  assert.match(read('package-lock.json'), /"left-pad": "\^1\.0\.0"/);
  assert.match(read('src-tauri/Cargo.lock'), /name = "log"\nversion = "1\.0\.0"/);
});

test('preserves every other byte of each file apart from the version', () => {
  const before = setup('1.0.0');
  bumpVersion(dir, '1.0.1');
  const expected = fixtures('1.0.0', {
    packageJson: '1.0.1',
    lockRoot: '1.0.1',
    lockPackage: '1.0.1',
    tauri: '1.0.1',
    cargoToml: '1.0.1',
    cargoLock: '1.0.1',
  });
  for (const rel of FILES) {
    assert.equal(read(rel), expected[rel], rel);
    assert.notEqual(read(rel), before[rel], `${rel} should have changed`);
  }
});

test('rejects a non-semver string', () => {
  const before = setup('1.0.0');
  for (const bad of ['1.0', 'v1.0.1', '1.0.1-beta', '1.0.x', '', ' 1.0.1']) {
    assert.throws(() => bumpVersion(dir, bad), /semver|X\.Y\.Z/i, bad);
  }
  for (const rel of FILES) assert.equal(read(rel), before[rel]);
});

test('rejects a major version of 0 and mentions the Microsoft Store rule', () => {
  setup('1.0.0');
  assert.throws(() => bumpVersion(dir, '0.9.0'), /Microsoft Store/);
});

test('rejects a version equal to the current one', () => {
  setup('1.4.0');
  assert.throws(() => bumpVersion(dir, '1.4.0'), /greater/i);
});

test('rejects a version lower than the current one', () => {
  setup('1.4.0');
  assert.throws(() => bumpVersion(dir, '1.3.9'), /greater/i);
});

test('treats 1.0.10 as greater than 1.0.9', () => {
  assert.ok(compareVersions('1.0.10', '1.0.9') > 0);
  assert.ok(compareVersions('1.0.9', '1.0.10') < 0);
  assert.equal(compareVersions('2.3.4', '2.3.4'), 0);
  assert.ok(compareVersions('2.0.0', '1.99.99') > 0);
  setup('1.0.9');
  assert.deepEqual(bumpVersion(dir, '1.0.10'), { from: '1.0.9', to: '1.0.10' });
});

test('refuses to write anything when the files disagree', () => {
  const before = setup('1.0.0', { cargoToml: '1.0.1' });
  assert.throws(() => bumpVersion(dir, '1.1.0'), /Cargo\.toml/);
  for (const rel of FILES) assert.equal(read(rel), before[rel], `${rel} must be unchanged`);
});

test('assertConsistent returns the shared version when all files agree', () => {
  setup('1.2.0');
  assert.equal(assertConsistent(readVersions(dir)), '1.2.0');
});

test('assertConsistent error names the files that differ', () => {
  setup('1.0.0', { tauri: '1.0.2', lockPackage: '1.0.3' });
  assert.throws(
    () => assertConsistent(readVersions(dir)),
    (err) =>
      /tauri\.conf\.json/.test(err.message) &&
      /package-lock\.json/.test(err.message) &&
      /1\.0\.2/.test(err.message) &&
      /1\.0\.3/.test(err.message),
  );
});

test('readVersions names the file when a version cannot be found', () => {
  setup('1.0.0');
  fs.writeFileSync(path.join(dir, 'src-tauri/Cargo.toml'), '[package]\nname = "app"\n');
  assert.throws(() => readVersions(dir), /Cargo\.toml/);
});

test('leaves the repo untouched when a replacement finds no match', () => {
  const before = setup('1.0.0');
  // Lock file where the app entry is not first: root entry regex still fine, but Cargo.lock has no "app" block.
  fs.writeFileSync(path.join(dir, 'src-tauri/Cargo.lock'), '[[package]]\nname = "log"\nversion = "1.0.0"\n');
  assert.throws(() => bumpVersion(dir, '1.0.1'), /Cargo\.lock/);
  for (const rel of FILES.filter((f) => f !== 'src-tauri/Cargo.lock')) {
    assert.equal(read(rel), before[rel], `${rel} must be unchanged`);
  }
});

test('assertTagMatches passes when the tag is v plus the version', () => {
  assert.doesNotThrow(() => assertTagMatches('1.0.1', 'v1.0.1'));
});

test('assertTagMatches fails when the tag does not match the version', () => {
  assert.throws(() => assertTagMatches('1.0.0', 'v1.0.1'), /v1\.0\.0/);
  assert.throws(() => assertTagMatches('1.0.1', '1.0.1'), /v1\.0\.1/);
  assert.throws(() => assertTagMatches('1.0.1', 'v1.0.10'), /v1\.0\.1/);
});
